apiVersion: v1
kind: Namespace
metadata:
  name: loki

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
        promtail:
          enabled: true
        grafana:
          enabled: true 
          sidecar:
            datasources:
              enabled: true
        monitoring: 
        selfMonitoring:
          podLogs:
            # -- Additional PodLogs labels
            # labels: { http_resp_code, http_method}
            # -- Additional pipeline stages to process logs after scraping
            # https://grafana.com/docs/agent/latest/operator/api/#pipelinestagespec-a-namemonitoringgrafanacomv1alpha1pipelinestagespeca
            additionalPipelineStages:
              - match: 
                selector: '{app="api123"}'
                stages: 
                  - json:
                      expressions:
                        log:
                  - json: 
                      source: log
                      expressions:
                        http_resp_code: code 
                        http_method: method
                  - labels:
                      http_resp_code:
                      http_method:
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true