apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lokipwdps
  namespace: loki
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-paramstore-secret-store  # Must match the ClusterSecretStore using ParameterStore
  target:
    name: lokipwdps
    creationPolicy: Owner
  # data:
    # - secretKey: loki-password
    #   remoteRef:
    #     key: /cluster-lab-1/logging/loki-pwd
    #     property: passkey
  dataFrom:
    - extract:
        key: /cluster-lab-1/logging/loki-pwd  # Must match the full name of the parameter in SSM Parameter Store
