apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: loki-stack
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.10.2
      helm:
        valueFiles:
          - $values/gitops/loki-stack/values.yaml
    - repoURL: https://github.com/hamletrp/k8s-tests.git
      targetRevision: HEAD
      ref: values  
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

## set via the values file instead
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: loki-ingress
#   namespace: loki
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Since TLS ends at NLB
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: loki.doordress.us
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: loki-stack-grafana
#             port:
#               number: 443
