apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-adm-pwd-ext
  namespace: loki
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: awssm-secret-store # must match your AWS ClusterSecretStore name
  target:
    name: loki-adm-pwd
    creationPolicy: Owner
  # data:
  #   - secretKey: loki-adm-pwd
  #     remoteRef:
  #       key: lokipwd
  dataFrom:
    - extract:
        key: lokipwd # ARN or name of the secret in AWS Secrets Manager
