apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcloud-secret-store
  namespace: loki
spec:
  provider:
    gcpsm:
      projectID: smart-valet-mobile
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: gcloud-secrete-sa  # must be annotated with IRSA role ARN