apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: default  # or your desired namespace
spec:
  replicas: 350
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      tolerations:
        - key: "karpenter.sh/capacity-type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "3600"]
