apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-test-connection"
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: ["curl", "-f", "http://my-service:8080/health"]
      restartPolicy: Never
