apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-doordress-us
  namespace: istio-system
spec:
  secretName: cert-doordress-us
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  commonName: doordress.us
  dnsNames:
    - doordress.us
    - "*.doordress.us"
