apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: my-namespace
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
      annotations:
        appmesh.k8s.aws/mesh: awsappmesh-1
        appmesh.k8s.aws/virtualNode: service-b-node
    spec:
      containers:
      - name: app-container
        image: myorg/service-b:latest
        ports:
        - containerPort: 8080
