apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-umbrella1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hamletrp/k8s-tests.git
    targetRevision: main
    path: argocd-apps/apps   # child apps live here
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
