apiVersion: v1
kind: Namespace
metadata:
  name: jaeger-system
  labels:
    gateway-access: "haproxy-prod-gateway"

---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbingo
  labels:
    gateway-access: "haproxy-prod-gateway"

---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-system
  labels:
    gateway-access: "haproxy-prod-gateway"

---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-system
  labels:
    gateway-access: "traefik-prod-gateway"

---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-infra
  labels:
    gateway-access: "traefik-prod-gateway"

---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    gateway-access: "traefik-prod-gateway"

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: networking

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: external-secrets


---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system


---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    gateway-access: "traefik-prod-gateway"

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cert-manager


---
apiVersion: v1
kind: Namespace
metadata:
  name: gradeapp-prod
---


