apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-adm-pwd-ext
  namespace: logging
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: awssm-secret-store # must match your AWS ClusterSecretStore name
  target:
    name: loki-adm-pwd
    creationPolicy: Owner
  # data:
  #   - secretKey: loki-adm-pwd
  #     remoteRef:
  #       key: lokipwd
  dataFrom:
    - extract:
        key: lokipwd # ARN or name of the secret in AWS Secrets Manager


--- 
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: awssm-secret-store # must match your AWS ClusterSecretStore name
  target:
    name: argocd-secret
    creationPolicy: Merge
  dataFrom:
    - extract:
        key: argocd-admin-secret # ARN or name of the secret in AWS Secrets Manager
  # data:
  #   - secretKey: password
  #     remoteRef:
  #       key: argocdpwd
  #       property: password
  