---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ap-abc-secretclass
  namespace: httpbingo
spec:
  provider: aws
  parameters:
    region: us-east-1
    # do not create the main file
    failOnAsis: "false"
    objects: |
      - objectName: prod/ap-abc/cred
        objectType: secretsmanager
        objectAlias: ap_abc_cred.json
        # jmesPath:
        #     - path: '"admin-user"'
        #       objectAlias: adminUser
        #     - path: '"admin-password"'
        #       objectAlias: adminPassword
  ## not stored as a k8s secret
  # secretObjects:
  #   - secretName: myapp-k8s-secret
  #     type: Opaque
  #     data:
  #       - objectName: myusername
  #         key: k8s-myusername
  #       - objectName: mypassword
  #         key: k8s-mypassword
