# Service Account with IAM Role annotation for AWS Load Balancer Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awsalb-load-balancer-controller-sa
  namespace: networking
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/AmazonEKSLoadBalancerControllerRole-cluster-lab-10

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-awssm-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/eso-awssm-irsa-role-cluster-lab-10

---
# Service Account with IAM Role annotation for AWS Load Balancer Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-sa
  namespace: networking
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/eks-alb-controller-role-cluster-lab-10
