# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karpenter-serving-cert
  namespace: karpenter
spec:
  secretName: karpenter-cert
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: karpenter-webhook.karpenter.svc
  dnsNames:
    - karpenter-webhook.karpenter.svc
    - karpenter-webhook.karpenter.svc.cluster.local
  issuerRef:
    name: karpenter-selfsigned-issuer
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
