apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: kube-system
spec:
  # amiFamily: AL2023
  amiFamily: Bottlerocket
  
  role: eksctl-cluster-lab-1-nodegroup-linu-NodeInstanceRole
  # instanceProfile: KarpenterInstanceProfile-cluster-lab-1

  # Required, discovers subnets to attach to instances
  subnetSelectorTerms:
    # - tags:
        # karpenter.sh/discovery: cluster-lab-1
    - id: subnet-0db1365a2014b47ad
    - id: subnet-0848f828ada8a28eb

  # Required, discovers security groups to attach to instances
  securityGroupSelectorTerms:
    # - tags:
    #     karpenter.sh/discovery: cluster-lab-1
    # - name: my-security-group
    - id: sg-0a87ac4e762758675

  # Required
  amiSelectorTerms:
    - alias: bottlerocket@latest
    # - alias: al2023@latest
    # - alias: al2@latest # <- GPU Optimized AMD AMI 
    # - tags:
    #     karpenter.sh/discovery: "${CLUSTER_NAME}"
    #     environment: test

  # Optional, propagates tags to underlying EC2 resources
  tags:
    team: hamletlab-team
    app: test-app
    # used by karpenter_controller_role conditional terminate instance
    karpenter.sh/discovery: "cluster-lab-1"
