apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  # amiFamily: AL2023
  amiFamily: Bottlerocket
  
  role: eksctl-cluster-lab-13-nodegroup-linu-NodeInstanceRole
  # instanceProfile: KarpenterInstanceProfile-cluster-lab-13

  # Required, discovers subnets to attach to instances
  subnetSelectorTerms:
    # - tags:
        # karpenter.sh/discovery: cluster-lab-13
    - id: subnet-0fe6c078d13f0d78d
    - id: subnet-03a8e4aa734ad2170
    - id: subnet-006514268f3082d5c
    - id: subnet-0bc5b30a323538579

  # Required, discovers security groups to attach to instances
  securityGroupSelectorTerms:
    # - tags:
    #     karpenter.sh/discovery: cluster-lab-13
    # - name: my-security-group
    - id: sg-0124b87f46fa25090

  # Required
  amiSelectorTerms:
    - alias: bottlerocket@latest
    # - alias: al2023@latest
    # - alias: al2@latest # <- GPU Optimized AMD AMI 
    # - tags:
    #     karpenter.sh/discovery: "${CLUSTER_NAME}"
    #     environment: test

  # Optional, propagates tags to underlying EC2 resources
  tags:
    team: hamletlab-team
    app: test-app
    # used by karpenter_controller_role conditional terminate instance
    karpenter.sh/discovery: "cluster-lab-13"
