clusterName: "cluster-lab-13"
clusterEndpoint: "https://C11B9587A82A3DD534C0DB3F9EC32C48.gr7.us-east-1.eks.amazonaws.com"
replicas: 2
webhookCertManager:
  enabled: false
serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-13
controller:
  env:
    - name: CLUSTER_NAME
      value: "cluster-lab-13"
    - name: CLUSTER_ENDPOINT
      value: "https://C11B9587A82A3DD534C0DB3F9EC32C48.gr7.us-east-1.eks.amazonaws.com"