apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.karpenter.sh
    # repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.5.0
    chart: karpenter
    helm:
      releaseName: karpenter
      values: |
        installCRDs: true
        clusterName: "cluster-lab-14"
        clusterEndpoint: "https://1720E41D5BABDD46FFDD4424A29D2E6C.gr7.us-east-1.eks.amazonaws.com"
        replicas: 2
        webhookCertManager:
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: letsencrypt-prod
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-14
        controller:
          env:
            - name: CLUSTER_NAME
              value: "cluster-lab-14"
            - name: CLUSTER_ENDPOINT
              value: "https://1720E41D5BABDD46FFDD4424A29D2E6C.gr7.us-east-1.eks.amazonaws.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
