apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.karpenter.sh
    targetRevision: "0.16.3"
    chart: karpenter
    helm:
      values: |
        settings:
          clusterName: "cluster-lab-3"
          clusterEndpoint: "https://ECCA9348483C83E16F35FD85BDFA2716.gr7.us-east-1.eks.amazonaws.com"
          interruptionQueueName: karpenter-interruption-queue
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-3
        controller:
          env:
            - name: CLUSTER_NAME
              value: "cluster-lab-3"
            - name: CLUSTER_ENDPOINT
              value: "https://ECCA9348483C83E16F35FD85BDFA2716.gr7.us-east-1.eks.amazonaws.com"

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
