apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.karpenter.sh
    targetRevision: "0.16.3"
    chart: karpenter
    helm:
      values: |
        clusterName: "cluster-lab-1"
        clusterEndpoint: "https://BA16A3C4AFEF1CBB3319D0FE4D14C2DF.gr7.us-east-1.eks.amazonaws.com"
        replicas: 2
        # webhookCertManager:
        #   enabled: true
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-1
        controller:
          env:
            - name: CLUSTER_NAME
              value: "cluster-lab-1"
            - name: CLUSTER_ENDPOINT
              value: "https://BA16A3C4AFEF1CBB3319D0FE4D14C2DF.gr7.us-east-1.eks.amazonaws.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
