clusterName: "cluster-lab-2"
clusterEndpoint: "https://BA16A3C4AFEF1CBB3319D0FE4D14C2DF.gr7.us-east-1.eks.amazonaws.com"
replicas: 2
webhookCertManager:
  enabled: false
serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-2
controller:
  env:
    - name: CLUSTER_NAME
      value: "cluster-lab-2"
    - name: CLUSTER_ENDPOINT
      value: "https://BA16A3C4AFEF1CBB3319D0FE4D14C2DF.gr7.us-east-1.eks.amazonaws.com"