apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sca
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hamletrp/k8s-tests.git
    path: auto-scaler/helm-chart
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
