apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-awssm-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/eso-awssm-irsa-role-cluster-lab-3

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: awssm-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-awssm-sa
            namespace: external-secrets