bootstrapPassword: "fuckingRancheeer" # initial admin password

hostname: rancher.itsnotrocketscience.tech 
replicas: 3

postDelete:
  enabled: false

ingress:
  enabled: false

extraTolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"