bootstrapPassword: "fuckingRancheeer" # initial admin password

hostname: rancher.itsnotrocketscience.tech  
replicas: 2 # Production-grade HA deployment

# ingress:
#   enabled: true
#   ingressClassName: alb                 # Or alb if you're using AWS ALB Ingress Controller
  # tls:
  #   source: secret                        # Options: secret, letsEncrypt, rancher
  #   secretName: tls-rancher-ingress       # Pre-created Kubernetes TLS secret


# ingress:
#   tls:
#     source: letsEncrypt
#     letsEncrypt:
#       email: your-email@example.com
#       ingressClass: nginx

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
