apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      api: my-api
      name: simple-webapp
  template:
    metadata:
      labels:
        api: my-api
    spec:
      tolerations:
        - key: workload-type
          operator: Equal
          value: regular
          effect: NoSchedule
      containers:
      - name: mycontainer
        image: kustomwebapp
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mykustom-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"