resources:
- deployment.yaml
- service.yaml

images:
  - name: kustomwebapp
    newName: devopsjourney1/mywebapp
    newTag: latest

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1