apiVersion: v1
kind: Namespace
metadata:
  name: httpbingo

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbingo
  namespace: argocd
spec:
  project: default
  source:
    chart: httpbingo
    repoURL: https://estahn.github.io/charts
    targetRevision: 0.1.1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: httpbingo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
