appName: gradeapp
port: 3000
image:
  registry: ghcr.io
  repo_name: hamletrp/kubernetes-cicd-tutorial
  tag: 3481f421dd6c856041a27b03a07e652970ed42dc
tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"
