appName: gradeapp
port: 3000
# image:
#   registry: ghcr.io
#   repo_name: hamletrp/kubernetes-cicd-tutorial
#   tag: 3c4cd831050e2501abd77f5c272121b3d684f8b2
image:
  registry: docker.io
  repo_name: hamuretto/gradeapp
  tag: 66f87ccc85830dda17aef7c4e0aa3628e97185e5
tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"
