appName: gradeapp
port: 3000
image:
  registry: ghcr.io
  repo_name: hamletrp/kubernetes-cicd-tutorial
  tag: 1b58a94540406de2e99156ff83a95a9cca27b6bf
tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"
