apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cluster-autoscaler
      repoURL: https://kubernetes.github.io/autoscaler
      targetRevision: 9.46.6
      helm:
        valueFiles:
          - $values/gitops/cluster-autoscaler/values.yaml
    - repoURL: https://github.com/hamletrp/k8s-tests.git
      targetRevision: HEAD
      ref: values    
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
