autoDiscovery:
  clusterName: cluster-lab-2 # cluster.local
  namespace: kube-system  # default
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}

awsRegion: "us-east-1"
cloudProvider: aws

rbac:
  serviceAccount:
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/eks-cluster-autoscaler-role-{{ .Values.autoDiscovery.clusterName }}
    create: true

replicaCount: 2

extraArgs:
  scale-down-enabled: true
  scale-down-unneeded-time: 3m
  scale-down-delay-after-add: 5m
