apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "productpage"
  gateways:
  - bookinfo-gateway
  http:
    - route:
        - destination:
            host: productpage
            subset: v1
          weight: 100   