apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-lab-11
  region: us-east-1
  version: "1.33"
  tags:
    environment: staging
    team: platform
    karpenter.sh/discovery: cluster-lab-11
    karpenter.sh/managed-by: "team-h"
    k8s.io/cluster-autoscaler/cluster-lab-11: owned

vpc:
  manageSharedNodeSecurityGroupRules: true

addons:
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: eks-pod-identity-agent
    version: latest 
  - name: aws-ebs-csi-driver
    serviceAccountRoleARN: arn:aws:iam::722249351142:role/AmazonEKS_EBS_CSI_DriverRole-cluster-lab-11
    version: latest
  - name: vpc-cni
    version: latest 

iam:
  withOIDC: true

managedNodeGroups:
  - name: linux-nodes-11
    instanceTypes: ["m5.large"]
    # instanceTypes: ["m5.large", "t3.medium"]
    # spot: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    volumeSize: 40
    maxPodsPerNode: 110
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-11-nodegroup-linu-NodeInstanceRole
    labels:
      cluster-autoscaler-enabled: "true"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-11: owned
    taints:
      - key: "workload-type"
        value: "core"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"
  - name: linux-nodes-11-2
    instanceTypes: ["m5.large", "t3.medium"]
    desiredCapacity: 2
    minSize: 2
    maxSize: 6
    volumeSize: 40
    maxPodsPerNode: 110
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-11-nodegroup-linu-NodeInstanceRole
    labels:
      cluster-autoscaler-enabled: "true"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-11: owned
    taints:
      - key: "workload-type"
        value: "regular"
        effect: "NoSchedule"