apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-lab-1
  region: us-east-1
  version: "1.33"
  tags:
    environment: staging
    team: platform
    karpenter.sh/discovery: cluster-lab-1
    karpenter.sh/managed-by: "team-h"
    k8s.io/cluster-autoscaler/cluster-lab-1: owned

vpc:
#   id: vpc-02fbb8bc18a79fb95
#   subnets:
#     private:
#       us-east-1a:
#         id: subnet-016b1cf2a4a267f5f
#       us-east-1b:
#         id: subnet-00f9f5f891b8e9e91
#       us-east-1c:
#         id: subnet-051648327001e7199
#     public:
#       us-east-1a:
#         id: subnet-0668029c4271426d8
#       us-east-1b:
#         id: subnet-076f08f5fc9f93de5
#       us-east-1c:
#         id: subnet-034622651ea9a18f5
#   clusterEndpoints:
#     publicAccess: true
#     privateAccess: true
  # sharedNodeSecurityGroup: "sg-024c81e8dd5e8d6c0"
  manageSharedNodeSecurityGroupRules: true

addons:
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: eks-pod-identity-agent
    version: latest 
  - name: aws-ebs-csi-driver
    serviceAccountRoleARN: arn:aws:iam::722249351142:role/AmazonEKS_EBS_CSI_DriverRole-cluster-lab-1
    version: latest
  - name: vpc-cni
    version: latest 

iam:
  withOIDC: true

managedNodeGroups:
  - name: linux-nodes-1
    instanceTypes: ["m5.large"]
    # instanceTypes: ["m5.large", "t3.medium"]
    spot: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 40
    maxPodsPerNode: 110
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-1-nodegroup-linu-NodeInstanceRole
    labels:
      cluster-autoscaler-enabled: "true"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-1: owned