apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-lab-13
  region: us-east-1
  version: "1.35"
  tags:
    environment: staging
    team: platform
    karpenter.sh/discovery: cluster-lab-13
    karpenter.sh/managed-by: "team-h"
    k8s.io/cluster-autoscaler/cluster-lab-13: owned
    kubernetes.io/cluster/cluster-lab-13: "owned" 
    ManagedBy: "eksctl"

vpc:
  manageSharedNodeSecurityGroupRules: true

addons:
  - name: coredns
    version: latest
    configurationValues: |
      tolerations:
        - key: "workload-type"
          operator: "Equal"
          value: "core"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  - name: kube-proxy
    version: latest
  - name: eks-pod-identity-agent
    version: latest 
  # # provisioned via terraform, due to limitations of configurationValues tolerations, afinity et
  # - name: aws-ebs-driver
  #   version: latest
  #   serviceAccountRoleARN: arn:aws:iam::722249351142:role/AmazonEKS_EBS_CSI_DriverRole-cluster-lab-13
  - name: vpc-cni
    version: latest 
    configurationValues: |
      env:
        ENABLE_PREFIX_DELEGATION: "true"
        WARM_PREFIX_TARGET: "1" # Keeps 1 full block of 16 IPs warm per node
        WARM_IP_TARGET: "1" # Backup pool for instant scheduling bursts
  - name: metrics-server
    version: v0.7.2-eksbuild.4
    configurationValues: |
      tolerations:
        - key: "workload-type"
          operator: "Equal"
          value: "core"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

iam:
  withOIDC: true

managedNodeGroups:
  - name: linux-nodes-13-v3
    # ssh: # deprecated for security reasons add 2ns sec group with tag that intefere with aws alb ctrlr
    #   allow: true
    #   publicKeyName: ssh-ec2-eks-private-subnet

    # Instantly grants secure console access without SSH keys or SGs
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-13-nodegroup-linu-NodeInstanceRole

    # ami: ami-0123456789abcdef0  # your custom EKS-compatible AMI
    instanceTypes: ["m5.large"]
    # ✅ Support multiple AZs by referencing multi-AZ subnets
    # availabilityZones: ["us-east-1a", "us-east-1b"]
    # overrideBootstrapCommand: |
    #   #!/bin/bash
    #   /etc/eks/bootstrap.sh my-cluster \
    #     --kubelet-extra-args '--node-labels=purpose=custom'
    # instanceTypes: ["m5.large", "t3.medium"]
    # spot: true
    # launchTemplate:
    #   id: lt-0d8a5c8a5fcbe8f53    
    #   version: "1"                        
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    # volumeSize: 40 # suggested >= 100 Gib This volume is for the OS and kubelet — not for pods.
    # volumeType: gp3 # gp2 (default), gp3, io1, etc.
    # volumeEncrypted: true
    # volumeKmsKeyID: arn:aws:kms:us-east-1:123456789012:key/abcd-efgh-ijkl
    ## 🧠 Bonus Tip: Monitor with kubelet_volume_stats
    # maxPodsPerNode: 110
    labels:
      cluster-autoscaler-enabled: "true"
      nodegroup: worker-nodes-core
      node-role.kubernetes.io/worker: ""
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-13: "owned"
    taints:
      - key: "workload-type"
        value: "core"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"

  - name: linux-nodes-13-2-v4
    # ssh: # deprecated for security reasons add 2ns sec group with tag that intefere with aws alb ctrlr
    #   allow: true
    #   publicKeyName: ssh-ec2-eks-private-subnet

    # Instantly grants secure console access without SSH keys or SGs
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-13-nodegroup-linu-NodeInstanceRole

    # ami: ami-0123456789abcdef0  # your custom EKS-compatible AMI
    instanceTypes: ["m5.large", "t3.medium"]
    # ✅ Support multiple AZs by referencing multi-AZ subnets
    # availabilityZones: ["us-east-1a", "us-east-1b"]
    desiredCapacity: 1
    minSize: 1
    maxSize: 6
    volumeSize: 40
    maxPodsPerNode: 110
    labels:
      cluster-autoscaler-enabled: "true"
      nodegroup: worker-nodes-regular
      node-role.kubernetes.io/worker: ""
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-13: "owned"
    taints:
      - key: "workload-type"
        value: "regular"
        effect: "NoSchedule"

  - name: linux-nodes-13-1-v1
    # ssh: # deprecated for security reasons add 2ns sec group with tag that intefere with aws alb ctrlr
    #   allow: true
    #   publicKeyName: ssh-ec2-eks-private-subnet

    # Instantly grants secure console access without SSH keys or SGs
    iam:
      instanceRoleARN: arn:aws:iam::722249351142:role/eksctl-cluster-lab-13-nodegroup-linu-NodeInstanceRole

    # ami: ami-0123456789abcdef0  # your custom EKS-compatible AMI
    instanceTypes: ["m5.large", "t3.medium"]
    # ✅ Support multiple AZs by referencing multi-AZ subnets
    # availabilityZones: ["us-east-1a", "us-east-1b"]
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 40
    maxPodsPerNode: 110
    labels:
      cluster-autoscaler-enabled: "true"
      nodegroup: worker-nodes-regular
      topology.kubernetes.io/zone: us-east-1a
      node-role.kubernetes.io/worker: ""
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-lab-13: "owned"
    taints:
      - key: "workload-type"
        value: "regular"
        effect: "NoSchedule"