apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd 
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.39.6
    helm:
      releaseName: argo-rollouts
      values: |
        installCRDs: true
        dashboard:
          enabled: true
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
        controller:
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

