apiVersion: v1
kind: Namespace
metadata:
  name: networking

---
# Argo CD Application to install AWS Load Balancer Controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awsalb-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: networking
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.2
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: cluster-lab-2
        region: us-east-1
        vpcId: vpc-0f61694ea6a6059d2
        ingressGroup:
          name: devops-group
        nameOverride: awsalb-load-balancer-controller
        replicaCount: 2
        autoscaling:
          enabled: false
          minReplicas: 2
          maxReplicas: 4
          targetCPUUtilizationPercentage: 80
        serviceAccount:
          create: false
          name: awsalb-load-balancer-controller-sa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

---
# Service Account with IAM Role annotation for AWS Load Balancer Controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awsalb-load-balancer-controller-sa
  namespace: networking
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/AmazonEKSLoadBalancerControllerRole-cluster-lab-2
