apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd  # Argo CD's namespace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.17.0  # Update to the latest version as needed
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-awssm-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::722249351142:role/eso-awssm-irsa-role-cluster-lab-2

## fails to be created auto
# ---
# apiVersion: external-secrets.io/v1
# kind: ClusterSecretStore
# metadata:
#   name: awssm-secret-store
#   namespace: external-secrets
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: us-east-1
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets-awssm-sa
#             namespace: external-secrets
