apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbingo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: httpbingo
      repoURL: https://estahn.github.io/charts
      targetRevision: 0.1.1
      helm:
        releaseName: httpbingo
        values: |
          replicaCount: 2
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
    - repoURL: https://github.com/hamletrp/k8s-tests.git
      targetRevision: HEAD
      ref: values 
  destination:
    server: https://kubernetes.default.svc
    namespace: httpbingo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
