apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/hamletrp/k8s-tests.git
    targetRevision: HEAD
    path: gitops/karpenter-root
    helm:
      valuesObject:
        karpenter:
          tolerations:  
            - key: "CriticalAddonsOnly"
              operator: "Exists"
            - key: "workload-type"
              operator: "Equal"
              value: "core"
              effect: "NoSchedule"
            # #   or tolerate all taints that exists
            - key: ""
              operator: "Exists"
              effect: "NoSchedule"
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::722249351142:role/KarpenterControllerRole-cluster-lab-11"
          settings:
            clusterName: "cluster-lab-11"
            interruptionQueue: "karpenter-interruption-queue-cluster-lab-11"
          controller: 
            replicas: 3
            resources:
              requests:
                cpu: 1
                memory: 1Gi
              limits:
                cpu: 1
                memory: 1Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true