apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.84.0 
    helm:
      releaseName: kiali
      values: |
        cr:
          deployment:
            serviceAccount:
              create: true
          auth:
            strategy: anonymous
          istio_namespace: istio-system

        rbac:
          create: true

        deployment:
          namespace: kiali-system
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"

        auth:
          strategy: anonymous  

        external_services:
          istio:
            rootNamespace: istio-system
            configMapName: ""   

          prometheus:
            url: prometheus-url

          grafana:
            enabled: true
            url: grafana-url

          tracing:
            enabled: true
            provider: jaeger
            url: jaeger-url

        server:
          accessible_namespaces:
            - "**"  # Allow viewing all namespaces in the cluster

        # Optional: enable service monitor if you want to scrape Kiali metrics
        prometheus:
          createPrometheusResource: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
