apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.84.0 # use the latest stable version or pin as needed
    helm:
      releaseName: kiali
      values: |
        cr:
          deployment:
            serviceAccount:
              create: true
          auth:
            strategy: anonymous
          istio_namespace: istio-system

        deployment:
          namespace: kiali-system
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"

        auth:
          strategy: anonymous  # Use "login" for prod, "anonymous" for test/dev

        external_services:
          istio:
            rootNamespace: istio-system
            configMapName: ""   # disables looking for configmap/istio

          prometheus:
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090

          grafana:
            enabled: true
            url: http://loki-stack-grafana.logging.svc.cluster.local:3000

          tracing:
            enabled: true
            provider: jaeger
            url: http://jaeger-query.jaeger-system.svc.cluster.local:16685

        server:
          accessible_namespaces:
            - "**"  # Allow viewing all namespaces in the cluster

        # Optional: enable service monitor if you want to scrape Kiali metrics
        prometheus:
          createPrometheusResource: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
