apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.84.0 # use the latest stable version or pin as needed
    helm:
      releaseName: kiali
      values: |
        deployment:
          namespace: kiali-system
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"

        auth:
          strategy: anonymous  # Use "login" for prod, "anonymous" for test/dev

        external_services:
          # prometheus:
          #   url: http://prometheus.istio-system.svc.cluster.local:9090

          grafana:
            enabled: true
            url: http://loki-stack-grafana.logging.svc.cluster.local:3000

          tracing:
            enabled: true
            provider: jaeger
            url: http://jaeger-query.istio-system.svc.cluster.local:16686

        server:
          accessible_namespaces:
            - "**"  # Allow viewing all namespaces in the cluster

        # Optional: enable service monitor if you want to scrape Kiali metrics
        prometheus:
          createPrometheusResource: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
