apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: loki-stack
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.10.2
      helm:
        releaseName: loki-stack
        valueFiles:
          - $values/gitops/loki-stack/values.yaml
    - repoURL: https://github.com/hamletrp/k8s-tests.git
      targetRevision: HEAD
      ref: values  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

