apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    chart: nginx-gateway-fabric
    targetRevision: 2.6.2
    helm:
      releaseName: nginx-gateway-fabric
      valuesObject:
        certGenerator:
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"

        nginxGateway:
          name: nginx-gateway-fabric
          gatewayClassName: nginx-gateway

          replicas: 1

          autoscaling:
            enable: true
            minReplicas: 1
            maxReplicas: 5
            targetCPUUtilizationPercentage: 70
            behavior:
              scaleDown:
                policies:
                - type: Pods
                  value: 1
                  periodSeconds: 180
              scaleUp:
                  policies:
                  - type: Pods
                    value: 2
                    periodSeconds: 60

          config:
            logging:
              level: info

          labels:
            infra-tier: "nginx-gateway-fabric" 

          tolerations:
          - key: "workload-type"
            operator: "Equal"
            value: "regular"
            effect: "NoSchedule"
            
        nginx:
          replicas: 2

          autoscaling:
            enable: true
            minReplicas: 2
            maxReplicas: 5
            targetCPUUtilizationPercentage: 50
            behavior:
              scaleDown:
                policies:
                - type: Pods
                  value: 1
                  periodSeconds: 180
              scaleUp:
                  policies:
                  - type: Pods
                    value: 2
                    periodSeconds: 60

          service:
            loadBalancerClass: "service.k8s.aws/nlb"

          debug: false

          pod:
            tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true