apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
    chart: nginx-gateway-fabric
    targetRevision: 2.6.2
    helm:
      releaseName: nginx-gateway-fabric
      valuesObject:
        certGenerator:
          tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
        nginxGateway:
          name: nginx-gateway-fabric
          gatewayClassName: nginx-gateway
          tolerations:
          - key: "workload-type"
            operator: "Equal"
            value: "regular"
            effect: "NoSchedule"
          pod:
            tolerations:
            - key: "workload-type"
              operator: "Equal"
              value: "regular"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true