apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: rancher
      repoURL: https://releases.rancher.com/server-charts/stable
      targetRevision: 2.11.2
      helm:
        releaseName: rancher
        valueFiles:
          - $values/gitops/rancher/rancher-values.yaml
        valuesObject:
          hostname: rancher.itsnotrocketscience.tech  
          replicas: 3
          bootstrapPassword: "fuckingRancheeerrrr"
          ingress:
            enabled: true
            ingressClassName: nginx
            tls:
              source: letsencrypt
          letsencrypt:
            email: hamletrp@gmail.com

    - repoURL: https://github.com/hamletrp/k8s-tests.git
      targetRevision: HEAD
      ref: values 
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
