apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-aws 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    chart: secrets-store-csi-driver-provider-aws
    targetRevision: 3.1.0
    helm:
      releaseName: secrets-store-csi-driver-provider-aws
      valuesObject:
        awsRegion: us-east-1
        
        ## default. matches secrets-store-csi-driver providersDir:
        # providerVolume: "/var/run/secrets-store-csi-providers"
        # kubeletPath: "/var/lib/kubelet"

        ## can install this too
        secrets-store-csi-driver:
          install: false
          # fullnameOverride: secrets-store-csi-driver
          # tokenRequests:
          #   - audience: "sts.amazonaws.com"
          #   - audience: "pods.eks.amazonaws.com"

        tolerations:
          - key: "workload-type"
            operator: "Equal"
            value: "regular"
            effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true