apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi-driver 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.6.0
    helm:
      releaseName: secrets-store-csi-driver
      valuesObject:
        tokenRequests:
          - audience: "sts.amazonaws.com"
          - audience: "pods.eks.amazonaws.com"

        linux:
          ## default: providers gRPC socket location on node
          # providersDir: /var/run/secrets-store-csi-providers
          # additionalProvidersDirs:
          #   - /etc/kubernetes/secrets-store-csi-providers
          driver:
            serviceAccountTokenInSecrets: false

          tolerations:
          - key: "workload-type"
            operator: "Equal"
            value: "regular"
            effect: "NoSchedule"

        syncSecret:
          enabled: false

        enableSecretRotation: true

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true