apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: colorteller-router
  namespace: appmesh-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  meshRef:
    name: awsappmesh-1
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: color-route
      httpRoute:
        match:
          prefix: "/"
        action:
          weightedTargets:
            - virtualNodeRef:
                name: colorteller-blue
              weight: 50
            - virtualNodeRef:
                name: colorteller-green
              weight: 50
