# argocd-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-acm-tls
  namespace: argocd
spec:
  secretName: argocd-acm-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.doordress.us"
