# clusterissuer-acm.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: hamletrp@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z09059223NU9ETJKGVT4I
            accessKeyID: AKIA2QKLKP7TOPH4CJXR
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: secret-access-key
