apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/myorg/gitops-repo
    targetRevision: HEAD
    path: gitops/apps/service-b
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
